[server]
address = "localhost:8081"
addressWithProtocol = "http://localhost:8081"
timeZone = ""

[database]
dsn = "postgres://user:example@localhost"

[testUsers]
adminUsername = "admin-user"
adminPassword = "admin-user-password"
boardAdminUsername = "test-user"
boardAdminPassword = "test-user-password"
unprivilegedUsername = "unprivileged-user"
unprivilegedPassword = "unprivileged-user-password"
votingUserUsername = "voting-user"
votingUserPassword = "voting-user-password"

[caching]
defaultCacheTime = 15
postList = 1
