[server]
address = "localhost:8081"
addressWithProtocol = "http://localhost:8081"

[database]
dsn = "postgres://user:example@localhost"

[testUsers]
boardAdminUsername = "test-user"
boardAdminPassword = "test-user-password"
unprivilegedUsername = "unprivileged-user"
unprivilegedPassword = "unprivileged-user-password"